/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AppSlugRouteImport } from './routes/app.$slug'
import { Route as OpenSlugRouteImport } from './routes/open.$slug'
import { Route as ApiPublicFileRouteImport } from './routes/api/public/file'
import { Route as ApiPublicIosSlugRouteImport } from './routes/api/public/ios.$slug'
import { Route as ApiPublicManifestSlugRouteImport } from './routes/api/public/manifest.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSlugRoute = AppSlugRouteImport.update({
  id: '/app/$slug',
  path: '/app/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenSlugRoute = OpenSlugRouteImport.update({
  id: '/open/$slug',
  path: '/open/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFileRoute = ApiPublicFileRouteImport.update({
  id: '/api/public/file',
  path: '/api/public/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIosSlugRoute = ApiPublicIosSlugRouteImport.update({
  id: '/api/public/ios/$slug',
  path: '/api/public/ios/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicManifestSlugRoute = ApiPublicManifestSlugRouteImport.update({
  id: '/api/public/manifest/$slug',
  path: '/api/public/manifest/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRoute
  '/developer': typeof DeveloperRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/app/$slug': typeof AppSlugRoute
  '/open/$slug': typeof OpenSlugRoute
  '/api/public/file': typeof ApiPublicFileRoute
  '/api/public/ios/$slug': typeof ApiPublicIosSlugRoute
  '/api/public/manifest/$slug': typeof ApiPublicManifestSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRoute
  '/developer': typeof DeveloperRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/app/$slug': typeof AppSlugRoute
  '/open/$slug': typeof OpenSlugRoute
  '/api/public/file': typeof ApiPublicFileRoute
  '/api/public/ios/$slug': typeof ApiPublicIosSlugRoute
  '/api/public/manifest/$slug': typeof ApiPublicManifestSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRoute
  '/developer': typeof DeveloperRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/app/$slug': typeof AppSlugRoute
  '/open/$slug': typeof OpenSlugRoute
  '/api/public/file': typeof ApiPublicFileRoute
  '/api/public/ios/$slug': typeof ApiPublicIosSlugRoute
  '/api/public/manifest/$slug': typeof ApiPublicManifestSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apps'
    | '/auth'
    | '/developer'
    | '/news'
    | '/profile'
    | '/app/$slug'
    | '/open/$slug'
    | '/api/public/file'
    | '/api/public/ios/$slug'
    | '/api/public/manifest/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apps'
    | '/auth'
    | '/developer'
    | '/news'
    | '/profile'
    | '/app/$slug'
    | '/open/$slug'
    | '/api/public/file'
    | '/api/public/ios/$slug'
    | '/api/public/manifest/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apps'
    | '/auth'
    | '/developer'
    | '/news'
    | '/profile'
    | '/app/$slug'
    | '/open/$slug'
    | '/api/public/file'
    | '/api/public/ios/$slug'
    | '/api/public/manifest/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppsRoute: typeof AppsRoute
  AuthRoute: typeof AuthRoute
  DeveloperRoute: typeof DeveloperRoute
  NewsRoute: typeof NewsRoute
  ProfileRoute: typeof ProfileRoute
  AppSlugRoute: typeof AppSlugRoute
  OpenSlugRoute: typeof OpenSlugRoute
  ApiPublicFileRoute: typeof ApiPublicFileRoute
  ApiPublicIosSlugRoute: typeof ApiPublicIosSlugRoute
  ApiPublicManifestSlugRoute: typeof ApiPublicManifestSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$slug': {
      id: '/app/$slug'
      path: '/app/$slug'
      fullPath: '/app/$slug'
      preLoaderRoute: typeof AppSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open/$slug': {
      id: '/open/$slug'
      path: '/open/$slug'
      fullPath: '/open/$slug'
      preLoaderRoute: typeof OpenSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/file': {
      id: '/api/public/file'
      path: '/api/public/file'
      fullPath: '/api/public/file'
      preLoaderRoute: typeof ApiPublicFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ios/$slug': {
      id: '/api/public/ios/$slug'
      path: '/api/public/ios/$slug'
      fullPath: '/api/public/ios/$slug'
      preLoaderRoute: typeof ApiPublicIosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/manifest/$slug': {
      id: '/api/public/manifest/$slug'
      path: '/api/public/manifest/$slug'
      fullPath: '/api/public/manifest/$slug'
      preLoaderRoute: typeof ApiPublicManifestSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppsRoute: AppsRoute,
  AuthRoute: AuthRoute,
  DeveloperRoute: DeveloperRoute,
  NewsRoute: NewsRoute,
  ProfileRoute: ProfileRoute,
  AppSlugRoute: AppSlugRoute,
  OpenSlugRoute: OpenSlugRoute,
  ApiPublicFileRoute: ApiPublicFileRoute,
  ApiPublicIosSlugRoute: ApiPublicIosSlugRoute,
  ApiPublicManifestSlugRoute: ApiPublicManifestSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
